[package]
name = "switchboard-agent"
version.workspace = true
license.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
switchboard-kernel.workspace = true
switchboard-uuids.workspace = true
thiserror.workspace = true
async-trait.workspace = true

[lints]
workspace = true
