[package]
name = "switchboard-infrastructure"
version.workspace = true
license.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
switchboard-application.workspace = true
switchboard-agent.workspace = true
switchboard-kernel.workspace = true
switchboard-uuids.workspace = true
async-trait.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["time"] }
tokio-util.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["net", "io-util"] }
axum.workspace = true

[lints]
workspace = true
