[package]
name = "switchboard-application"
version.workspace = true
license.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[features]
default = []
mocks = ["dep:mockall"]

[dependencies]
switchboard-kernel.workspace = true
switchboard-uuids.workspace = true
switchboard-agent.workspace = true
async-trait.workspace = true
thiserror.workspace = true
mockall = { workspace = true, optional = true }

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
