---
name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: '0'
  RUST_BACKTRACE: '1'

jobs:
  fmt:
    if: >-
      ${{ !(startsWith(github.head_ref, 'release-please--')
      && github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-repo
      - run: cargo fmt --all -- --check

  lint:
    if: >-
      ${{ !(startsWith(github.head_ref, 'release-please--')
      && github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-repo
      - run: cargo clippy --workspace --all-targets --all-features -- -D warnings

  test:
    if: >-
      ${{ !(startsWith(github.head_ref, 'release-please--')
      && github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-repo
      - run: cargo nextest run --workspace --all-features --no-fail-fast

  rustdoc:
    if: >-
      ${{ !(startsWith(github.head_ref, 'release-please--')
      && github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-repo
      - run: cargo doc --workspace --all-features --no-deps

  audit:
    if: >-
      ${{ !(startsWith(github.head_ref, 'release-please--')
      && github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-repo
      - run: cargo deny --all-features check

  taplo:
    if: >-
      ${{ !(startsWith(github.head_ref, 'release-please--')
      && github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-repo
      - run: taplo fmt --check

  typos:
    if: >-
      ${{ !(startsWith(github.head_ref, 'release-please--')
      && github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-repo
      - run: typos
